### ISSUE TITLE
Bad content 

### ISSUE THREAD

**Issue by theo-donacik** [AT-Blaze/AT-Blaze.github.io#1]
The site works fine but the content on it sucks

**Comment by AT-Blaze** [comment]
Hi Theo!

I'm sorry to hear that! I appreciate your feedback on the site though. I'm publishing a new blog today if you want to take a look.

**Comment by AT-Blaze** [comment]
Hi Theo, I just wanted to follow up on this. I've made some changes to my blog, including some new posts, and an audio post. Let me know if you enjoy them and hopefully we can resolve this issue!

**Comment by AT-Blaze** [comment]
Hi Theo, I haven't heard back from you on the content of my website but I've made quite a few edits since your first comment so I will mark this issue as resolved. If you have any more issues please feel free to create a new one!
